### ISSUE TITLE
Doesn't work on Java 8

### ISSUE THREAD

**Issue by Stexxen** [eishay/jvm-serializers#46]
Unfortunately it doesn't compile under java 8.
First problem was the Scala version (2.8) is incompatible. I upgraded the support compiler to 2.11 but that doesn't work at all, as some required annotations have been removed (@serialization)
2.10 seems to get further ( The annotations are present, but deprecated) but I then blows up at another error

```
error: bad symbolic reference. A signature in Generic.class refers to type Collection
in package scala.package which is not available.
It may be completely missing from the current classpath, or the version on
the classpath might be incompatible with the version used when compiling Generic.class.
```

**Comment by pascaldekloe** [comment]
Works with Java 8 now.
