### ISSUE TITLE
Check Results

### ISSUE THREAD

**Issue by dturanski** [eishay/jvm-serializers#53]
The latest version of the wiki shows total times that seem to be an order of magnitude higher than previously reported.  The results from running on my macbook pro are also more in line with previous results.

![screen shot 2015-09-09 at 1 08 11 pm](https://cloud.githubusercontent.com/assets/886859/9768786/ea2eba82-56f3-11e5-9798-74a9d2318eb1.png)

**Comment by pascaldekloe** [comment]
Agreed @dturanski. Happy with the new values?
https://github.com/eishay/jvm-serializers/wiki
