### ISSUE TITLE
include capnproto

### ISSUE THREAD

**Issue by geoffreywiseman** [eishay/jvm-serializers#64]
I'd love to see where capnproto falls in here...
https://capnproto.org

**Comment by cakoose** [comment]
I haven't followed CapnProto recently, but I think there were three ways of
implementing the library -- JNI, sun.misc.Unsafe, and safe.  Would be
interesting to see the comparison.

If anyone wants to implement it, I can provide help with the benchmark
framework and stuff.

On Thu, Mar 24, 2016 at 11:25 AM, Geoffrey Wiseman <notifications@github.com

**Comment by zapov** [comment]
I've included Flatbuffers here: https://github.com/eishay/jvm-serializers/pull/63

but it really calls for removal of POJO garbage :/

I can also add Capnproto if nobody else wants to :D

**Comment by zapov** [comment]
I've updated my PR with Capnproto.

**Comment by pascaldekloe** [comment]
Done with #63.
