### ISSUE TITLE
Add support for Non-ASCII characters?

### ISSUE THREAD

**Issue by fishercoder1534** [eishay/jvm-serializers#68]
This might be a dumb question, I'm not able to run this project with non-ASCII test case, but as the wiki says, it should be.

The wiki says: "Other test data will yield different results (e.g. adding a non ascii char to every string :-) ). "

And I used one non-ascii word in the test, but got "invalid character in string literal: #c2a4", here's how I'm using it:

Images = [
		{
			Uri = "http://javaone.com/keynote_large.jpg"
			Title = Set: "14K 스와로브스키 시그니티 1캐럿 목걸이_NC110"
			Width = 1024
			Height = 768
			Size = Large
		}
		{
			Uri = "http://javaone.com/keynote_large.jpg"
			Title = Set: "보쉬 두루마리 100P 파우치세트 드릴비트 100PCS 보쉬 100PCS GSB10RE "
			Width = 1024
			Height = 800
			Size = Large
		}
]

It's complaining at this line: 			Title = Set: "14K 스와로브스키 시그니티 1캐럿 목걸이_NC110"

The `Title` field is String.

How can I enable non-ASCII for testing?

Thanks a lot!

**Comment by cakoose** [comment]
I think non-ASCII used to work, so maybe something broke...  I'll test
later tonight.

**Comment by fishercoder1534** [comment]
@cakoose Thanks! I'm looking forward to your reply.

**Comment by fishercoder1534** [comment]
Ping... sorry for pushing it. But any updates would be greatly appreciated!

**Comment by cakoose** [comment]
Sorry, it took a little more work than I thought it would.

I pushed a fix.  You now specify the test files in ".json" files (instead
of ".cks" files).  The format is standard JSON except "//" comments are
allowed.

("cks" was a format I worked on several years ago...  I haven't kept it
updated so I decided to just remove it.)

**Comment by fishercoder1534** [comment]
Excellent! Thanks so much for your effort! It helped me a lot! @cakoose
