### ISSUE TITLE
delete (dealloc) time missing from performance wiki

### ISSUE THREAD

**Issue by KjellKod** [eishay/jvm-serializers#74]
Hi, 

the create time is visible in the performance breakdown but not the deallocation time. For applications which huge number of object creation the object deletion might be just as important for the performance.

**Comment by cakoose** [comment]
I don't know a good way to measure deallocation time with garbage collected
memory.

For manually managed (or ref-counted) memory, deallocation time is
proportional to the amount of memory being deallocated.  For garbage
collected memory, the deallocation time is affected by the amount of live
memory as well, which makes it harder to measure.

One idea is to run the JVM with a small heap, to make sure garbage
collection would be triggered multiple times in a single test run.  This
way, deallocation time is included in the overall running time measurement.

Do identify the deallocation time, maybe you could also run the benchmark
with a large heap and see what the difference is.  I'm not sure how precise
this would be.
