### ISSUE TITLE
Make is failing

### ISSUE THREAD

**Issue by shankyty** [eishay/jvm-serializers#75]
make details
GNU Make 3.81
Copyright (C) 2006  Free Software Foundation, Inc.
This is free software; see the source for copying conditions.
There is NO warranty; not even for MERCHANTABILITY or FITNESS FOR A
PARTICULAR PURPOSE.

This program built for i386-apple-darwin11.3.0

error when i do make in tpc folder

`build/bytecode/main/serializers/stephenerialization/MediaStephenerializer.java:41: warning: [unchecked] unchecked cast
                object.setPersons((java.util.List<java.lang.String>) stream.readObject());
                                                                                      ^
  required: List<String>
  found:    Object
build/bytecode/main/serializers/stephenerialization/MediaContentStephenerializer.java:23: warning: [unchecked] unchecked cast
                object.setImages((java.util.List<serializers.stephenerialization.Image>) stream.readObject());
                                                                                                          ^
  required: List<Image>
  found:    Object
warning: Implicitly compiled files were not subject to annotation processing.
  Use -proc:none to disable annotation processing or -implicit to specify a policy for implicit compilation.
4 warnings`

**Comment by cakoose** [comment]
Those messages are warning messages.  The build can still complete successfully even if there are warning messages.

To see if the build completed successfully, run `echo $?` after `make` completes.  If you get `0`, then the build was successful.  If you get a number higher than zero, there was an error.

**Comment by shankyty** [comment]
Yes got it worked for me.
