### ISSUE TITLE
Add Moshi

### ISSUE THREAD

**Issue by hendrawd** [eishay/jvm-serializers#77]
Can you add Moshi from Square https://github.com/square/moshi as one of the serializer and compare it with the others?

**Comment by cakoose** [comment]
Typically, new libraries are added when someone takes an interest, writes the code, and submits a pull request.

If you're interested in adding it, it's relatively straightforward.  You can look at one of the existing examples, e.g. [JsonGsonDatabind.java](https://github.com/eishay/jvm-serializers/blob/master/tpc/src/serializers/json/JsonGsonDatabind.java).  If you run into any issues, we're happy to help.
