### ISSUE TITLE
Can't seem to find the referenced Avro media classes: Image, Media, and MediaContent

### ISSUE THREAD

**Issue by wintsonpryme** [eishay/jvm-serializers#79]
The serializers in the serializers.avro directory all have media imports that do not exist in the library.
The media sub-directory under the serializers.avro directory does not exist.
Here are the non-existent imports:

import serializers.avro.media.Image;
import serializers.avro.media.Media;
import serializers.avro.media.MediaContent;

What am I missing?

**Comment by cowtowncoder** [comment]
Project is built using `make`, so do that. It will generate and compile various classes.
