### ISSUE TITLE
Add Amazon Ion

### ISSUE THREAD

**Issue by phraktle** [eishay/jvm-serializers#84]
It would be nice to see [Amazon Ion](https://github.com/amzn/ion-java) added to the benchmarks.

**Comment by pascaldekloe** [comment]
Make a pull request please.

**Comment by phraktle** [comment]
Yes, someone make a pull request, please :)

**Comment by pascaldekloe** [comment]
Every codec is "interesting" to see. No point in making issues for each, unless you're contributing.

**Comment by cowtowncoder** [comment]
One suggestion if someone is interested enough to spend the little bit of time necessary: aside from Amazon's Ion codec itself, there is Jackson backend, included as part of:

https://github.com/FasterXML/jackson-dataformats-binary

that should represent efficiency of the codec (it uses Amazon's codec in streaming mode under the hood) fairly well. Jackson binary formats package is already depended on for CBOR and Smile tests, so starting with test case for one or the other should take care of most of the work. So, add maven dependency, copy-paste test, change `SmileMapper`/`SmileFactory` to matching Ion-backed, and that should be it.
